project/urls.py
from django.contrib import admin
from django.urls import path ,include

from django.conf import settings 
from django.conf.urls.static import static


urlpatterns = [
    path('boss/', admin.site.urls),
    path('', include("simple.urls")),
    path('user/', include("user.urls")),
    path('account/', include("django.contrib.auth.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)


simple/urls.py
from django.urls import path, re_path
from .views import open, paras, register, database,  single, update, delete

app_name = "simple"

urlpatterns = [
    path("", open, name = "open"),
    path("paras/<str:pk>", paras , name = "paras"),
    path("database", database , name = "database"),
    path("single/<str:num>", single , name = "single"),
    path("register/", register , name = "register"),
    path("update/<str:pk>", update , name = "update"),
    path("delete/<str:pk>", delete , name = "delete"),
]


user/urls.py
from django.urls import path, re_path
from .views import logoutUser, myprofile, profile, profileform, signupUser, userProfile, loginUser
app_name = "user"

urlpatterns = [
    path("profilelist/", profile, name = "profile"),

    path("profileform/", profileform, name = "profileform"),

    path("myprofile/", myprofile, name = "myprofile"),

    path("loginform/", loginUser, name = "loginform"),
    path("logout/", logoutUser, name = "logout"),

    path("userprofile/<uuid:pk>/", userProfile, name = "userprofile"),

    path('signup/', signupUser, name='signup')
    
]


simple/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

from django.db.models.deletion import CASCADE

from user.models import Profile

# Create your models here.

class Project(models.Model):

    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)

    title = models.CharField(max_length = 200)
    description = models.TextField(null=True, blank= True)
    featured_image = models.ImageField(null=True, blank=True, default = "default.jpg")
    demo_link = models.CharField(max_length=200, blank=True, null=True)
    source_link = models.CharField(max_length=2000, blank=True, null=True)
    tag = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, blank=True, null=True)
    vote_ratio = models.IntegerField(default=0, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique= True , primary_key=True, editable=False)
    
    def __str__(self):
        return self.title

class Reviews(models.Model):
    VOTE_TYPE = ( 
        ("up","Up Vote"),
        ("down","Down Vote"),
    )
    # owner
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length = 150, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique= True , primary_key=True, editable=False)
    

    def __str__(self):
        return self.value

class Tag(models.Model):
    name = models.CharField(max_length = 150)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique= True , primary_key=True, editable=False)
    


    def __str__(self):
        return self.name
            
class Signup(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    


        


simple/forms.py
# THE CREATE UPDATE AND DELETE  
from django.db.models import fields
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User

from .models import Project, Signup

class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['title', 'description', 'featured_image', 'demo_link', 'source_link', 'tag']
        widgets = {
            'tag':forms.CheckboxSelectMultiple()
        }

    # THIS IS TO CHANGE THE ATTRS IN THE FORM IN THE HTML FILE
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs.update({'class': 'input input--text', 'placeholder':"Add title"})

        self.fields['description'].widget.attrs.update({'class': 'input input--text', 'placeholder':"Add title"})

        self.fields['featured_image'].widget.attrs.update({'class': 'input input--text', 'placeholder':"Add title"})

        self.fields['demo_link'].widget.attrs.update({'class': 'input input--text', 'placeholder':"Add title"})

        self.fields['source_link'].widget.attrs.update({'class': 'input input--text','placeholder':"Add title"})


        self.fields['tag'].widget.attrs.update({'class': 'input input--text', 'placeholder':"Add title"})
 


    # THIS IS TO MAKE THINGS FASTER
        # for name, field in self.register.items():
        #     field.widget.attrs.update({'class':'input'})
         
        

class SignupForm(ModelForm):
    class Meta:
        model = User
        # fields = "__all__"
        fields = ("first_name", "username", "email", "password", )

simple/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from .models import Project , Tag
from .forms import ProjectForm, SignupForm

from django.contrib.auth.decorators import login_required

# Create your views here.

projectlist=[
    {
        "id" : "1" ,
        "title" : "Ecommerce Website" ,
        "description" : "Full functional Website"
    },  
    {
        "id" : "2" ,
        "title" : "Social Network" ,
        "description" : "Nice Work i am still working on"
    },
    {
        "id" : "3" ,
        "title" : "Port Website" ,
        "description" : "Portfolio functional Website"
    },
]

def open(request):
    my_dict = {
        "firstname" : "Temitope",
        "lastname" : "James",
        "nickname" : "Mufasa",
        "project" : projectlist

    }
    return render(request, "simple/open.html", context=my_dict)

def wow(request, fig):

    return HttpResponse("This is the response and this is the para: "+fig+" ")    

def paras(request, pk):
    projectobj = None
    for i in projectlist:
        if i['id'] == pk:
            projectobj = i
    dict = { "pk" : pk, "obj":projectobj}

    return render(request, "simple/paras.html", context = dict)
    
def database(request):
    project = Project.objects.all()
    return render(request, "simple/database.html", {"project":project,})

def single(request, num):
    projectobj = Project.objects.get(id=num)
    tags = projectobj.tag.all()

    mydict = { "tags" : tags, "num":num, "obj":projectobj}
    return render(request, "simple/single.html", context=mydict)

@login_required(login_url='user:loginform')
def register(request):
    registerForm = ProjectForm()

    if request.method == 'POST':
        # print(request.POST["title"])
        registerForm = ProjectForm(request.POST, request.FILES)
        if registerForm.is_valid():
            registerForm.save()      
            return redirect("simple:database")
    
    my_dict = {"register" : registerForm,}
    return render(request, "forms/register.html", context=my_dict)
@login_required(login_url='user:loginform')
def update(request, pk):
    projectid = Project.objects.get(id=pk)
    registerForm = ProjectForm(instance=projectid)

    if request.method == 'POST':
        # print(request.POST["title"])
        registerForm = ProjectForm(request.POST, request.FILES, instance=projectid)

        if registerForm.is_valid():
            registerForm.save()      
        return redirect("simple:database" )
    
    my_dict = {"register" : registerForm,}
    return render(request, "forms/edit.html", context=my_dict)

@login_required(login_url='user:loginform')
def delete(request, pk):
    project = Project.objects.get(id =pk)
    if request.method == "POST":
        project.delete()
        return redirect("simple:database")

    my_dict = {
        "object":project
    }
    return render(request, "forms/delete.html", my_dict)
    

    

templates/simple/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css"> -->
    
  <title>
      {% block title %}
      {% endblock title %}
  </title>
</head>
    
<body>
    <header class="header">
        <div class="container container--narrow">
          <a href="{% url 'simple:database' %}" class="header__logo">
            <img src="{% static 'images/icon.svg' %}" alt="DevSearch Logo" />
          </a>
          <nav class="header__nav">
            <input type="checkbox" id="responsive-menu" />
            <label for="responsive-menu" class="toggle-menu">
              <span style="color: red;">Menu</span>
              <div class="toggle-menu__lines"></div>
            </label>
            <ul class="header__menu">
              {% if request.user.is_authenticated %}
              <li class="header__menuItem"><a href="{% url 'simple:register' %}">Add Post</a></li>
              {% endif %}
              <li class="header__menuItem"><a href="{% url 'simple:database' %}">Projects</a></li>
              <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
              <li class="header__menuItem"><a href="{% url 'user:profile' %}">Profile List</a></li>

              {% if request.user.is_authenticated %}

              <li class="header__menuItem"><a href="{% url 'user:logout' %}" class="btn btn--sub">Logout</a></li>

              {% else %}

              <li class="header__menuItem"><a href="{% url 'user:signup' %}" class="btn btn--sub">Signup</a></li> 
              <li class="header__menuItem"><a href="{% url 'user:loginform' %}" class="btn btn--sub">Login</a></li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </header>


  <!-- THIS IS TO CHECK THE USER AUTHENTICATION -->
    <center><h2>
    {% if request.user.is_authenticated %}
      User is Logged In  
      {% else %}
      User is Logged Out  
    {% endif %}
    </h2></center>

    <!-- THIS IS FOR FLASH MESSAGES -->
    <!-- {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
              {{ message }}
          </li>
          {% endfor %}
      </ul>
    {% endif %} -->


    <div class="container">
        {% block things %}
        {% endblock %}
    </div>



<all>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
    <script src="{% static 'uikit/app.js' %}" > </script>
</all>
</body>
</html>

templates/simple/database.html
<!DOCTYPE html>
{% extends "simple/base.html" %}
{% load static %}
{% block things %}
<title>Database</title>

<!-- THIS IS FOR THE SEARCH BAR -->
<main class="projects">
  <section class="hero-section text-center">
    <div class="container container--narrow">
      <div class="hero-section__box">
        <h2>Search for <span>Projects</span></h2>
      </div>

      <div class="hero-section__search">
        <form class="form" method="get">
          <div class="form__field">
            <label for="formInput#search">Search By Data </label>
            <input class="input input--text" id="formInput#search" type="text" name="text"
              placeholder="Search by Project Title" />
          </div>

          <input class="btn btn--sub btn--lg" type="submit" value="Search" />
        </form>
      </div>
    </div>
  </section>


<!-- THIS IS FOR THE PROJECTS -->
<section class="projectsList">
    <div class="container">
      <div class="grid grid--three">
          {% for i in project  %}
            
         <div class="column">
          <div class="card project">
            <a href="{% url 'simple:single' i.id  %}" class="project">
              <img class="project__thumbnail" src="{{ i.featured_image.url }}" alt="project thumbnail" />
              '<div class="card__body">'
                <h3 class="project__title ititle">{{i.title}}</h3>
                <p><a class="project__author" href="{% url 'user:userprofile' i.id %}">{{ i.owner.name }}</a></p>
      <!-- <h1>The Project ID: {{ i.id }}</h1> -->
      <!-- <br> -->
      <!-- <h1>The Project Owner ID:{{ i.owner.id }}</h1> -->
                <p class="project--rating">
                  <span style="font-weight: bold;">{{i.vote_ratio}}%</span> Postitive
                  Feedback ({{i.vote_total}} Vote{{i.vote_total|pluralize:'s'}})
                </p>
                <div class="project__tags">

{% for tag in i.tag.all  %}
                <span class="tag tag--pill tag--main">
                  <small>{{tag}}</small>
                </span>
{% endfor %}

                </div>
              </div>
            </a>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
</section>


{% endblock things %}


<table style="width: 100%;">
    <tr>
        <th>Project</th>
        <th>Positive Votes</th>
        <th>Votes</th>
        <th>Created</th>
        <!-- <th>Edit</th> -->
    </tr>
    {% for i in project  %}
    <tr>
        <td><a href="{% url 'simple:single' i.id %}">{{i.title}}</a></td>
        <td>{{i.vote_ratio}}%</td>
        <td>{{i.vote_total}}</td>
        <td>{{i.created}}</td>
        <td><a href="{% url 'simple:update' i.id %}">Edit</a></td>
        <td><a href="{% url 'simple:delete' i.id %}">Delete</a></td>
    </tr>
    {% endfor %}
</table>





templates/simple/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top">
    <a class="navbar-brand">Brand</a>
    <button class="navbar-toggler" data-target="#my-nav" data-toggle="collapse" aria-controls="my-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div id="my-nav" class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Item 1 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Item 2</a>
            </li>
        </ul>
    </div>
</nav>

templates/simple/open.html
<!DOCTYPE html>
{% extends "simple/base.html" %}
{% load static %}

{% block things %}
<!-- {% include "simple/navbar.html" %} -->
<title>Test</title>
<h2><center>Hello There</center></h2>
{%if firstname == "Temitope"%}
<h2><center>{{firstname}}</center></h2>
<h2><center>{{lastname}}</center></h2>
<h2><center>{{nickname}}</center></h2>
{%else%}
<center><h2>There is no one here</h2></center>
{%endif%}
<br>

<ul>
    {%for project in project%}
        <li>Name: {{project.description}}<a href="{% url 'simple:paras' project.id %}">Paras[{{ project.id}}]</a></li>
            {%endfor%}
</ul>











{% endblock %}

templates/simple/paras.html
<!DOCTYPE <html>
<title>Params</title>
{% extends "simple/base.html" %}
{% load static %}
{% block things %}
    <center><h2>{{ pk }}</h2></center>
    <center><h2>{{ obj }}</h2></center>
    <br><br>

<ul>
    {% if obj %}
    <center><h4>This is Number {{obj.id}}</h4></center>
    <h2> title: {{ obj.title }}...{{obj.description }}</h2>
</ul>
    
    {% else %}
    <center>This place is empty</center>
    {% endif %}
    
<center><h1><a href="{% url 'simple:open' %}">Back to Paras</a></h1></center>


{% endblock %}

templates/simple/single.html
<!DOCTYPE html>
{% extends "simple/base.html" %}
{% load static %}
{% block things %}
<title>Single Project</title>

<main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle">Tools & Stacks</h3>
          <div class="singleProject__toolStack">
            {% for j in tags %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{j}}</small>
            </span>
            {% endfor %}
          </div>
          {% if obj.source_link %}
            
          <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>{{obj.source_link}}
          </a>
          {% else %}
          Demo Link: <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>{{obj.demo_link}}
          </a>
          {% endif %}
        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" src="{{ obj.featured_image.url }}" alt="portfolio thumbnail" />

          <div id="edit&delete Buttons">
            <a href="{% url 'simple:update' obj.id %}"><button type="submit" class="btn btn-primary">Edit</button></a>
            <a href="{% url 'simple:delete' obj.id %}"><button type="submit" class="btn btn-danger">Delete</button></a>
          </div>

          <a href="{% url 'user:userprofile' obj.owner.id %}" class="singleProject__developer">{{obj.owner}}</a>
          <h2 class="singleProject__title">{{obj.title}}</h2>
          <h3 class="singleProject__subtitle">About the Project</h3>
          <div class="singleProject__info">
            {{obj.description}}
          </div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>
            <h5 class="project--rating">
              {{obj.vote_ratio}}% Postitive Feedback ({{obj.vote_total}} Vote{{obj.vote_total|pluralize:'s'}})
            </h5>

            <form class="form" action="#" method="POST">
              <!-- Textarea -->
              <div class="form__field">
                <label for="formInput#textarea">Comments: </label>
                <textarea class="input input--textarea" name="message" id="formInput#textarea"
                  placeholder="Write your comments here..."></textarea>
              </div>
              <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
            </form>
            <div class="commentList">
              <div class="comment">
                <a href="profile.html">
                  <img class="avatar avatar--md"
                    src="https://pbs.twimg.com/profile_images/1335382240931368961/b3wSZKj4_400x400.jpg" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="profile.html" class="comment__author">Sulamita Ivanov</a>
                  <p class="comment__info">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit alias numquam perferendis
                    mollitia minus minima exercitationem possimus ab deserunt qui, soluta iusto doloribus eveniet
                    similique consequuntur ratione, dignissimos ut magni laborum quo.
                  </p>
                </div>
              </div>
              <div class="comment">
                <a href="profile.html">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/33843378" alt="user" />
                </a>
                <div class="comment__details">
                  <a href="profile.html" class="comment__author">Dennis Ivanov</a>
                  <p class="comment__info">
                    Consectetur adipisicing elit. Reprehenderit alias numquam perferendis mollitia minus minima
                    exercitationem possimus ab deserunt qui, ratione, dignissimos ut magni laborum quo.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</main>


{% endblock things %}
 