project/urls.py
from django.contrib import admin
from django.urls import path ,include

from django.conf import settings 
from django.conf.urls.static import static


urlpatterns = [
    path('boss/', admin.site.urls),
    path('', include("simple.urls")),
    path('user/', include("user.urls")),
    path('account/', include("django.contrib.auth.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)


simple/urls.py
from django.urls import path, re_path
from .views import open, paras, register, database,  single, update, delete

app_name = "simple"

urlpatterns = [
    path("", open, name = "open"),
    path("paras/<str:pk>", paras , name = "paras"),
    path("database", database , name = "database"),
    path("single/<str:num>", single , name = "single"),
    path("register/", register , name = "register"),
    path("update/<str:pk>", update , name = "update"),
    path("delete/<str:pk>", delete , name = "delete"),
]


user/urls.py
from django.urls import path, re_path
from .views import logoutUser, myprofile, profile, profileform, signupUser, userProfile, loginUser
app_name = "user"

urlpatterns = [
    path("profilelist/", profile, name = "profile"),

    path("profileform/", profileform, name = "profileform"),

    path("myprofile/", myprofile, name = "myprofile"),

    path("loginform/", loginUser, name = "loginform"),
    path("logout/", logoutUser, name = "logout"),

    path("userprofile/<uuid:pk>/", userProfile, name = "userprofile"),

    path('signup/', signupUser, name='signup')
    
]


simple/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

from django.db.models.deletion import CASCADE

from user.models import Profile

# Create your models here.

class Project(models.Model):

    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)

    title = models.CharField(max_length = 200)
    description = models.TextField(null=True, blank= True)
    featured_image = models.ImageField(null=True, blank=True, default = "default.jpg")
    demo_link = models.CharField(max_length=200, blank=True, null=True)
    source_link = models.CharField(max_length=2000, blank=True, null=True)
    tag = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, blank=True, null=True)
    vote_ratio = models.IntegerField(default=0, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique= True , primary_key=True, editable=False)
    
    def __str__(self):
        return self.title

class Reviews(models.Model):
    VOTE_TYPE = ( 
        ("up","Up Vote"),
        ("down","Down Vote"),
    )
    # owner
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length = 150, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique= True , primary_key=True, editable=False)
    

    def __str__(self):
        return self.value

class Tag(models.Model):
    name = models.CharField(max_length = 150)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique= True , primary_key=True, editable=False)
    


    def __str__(self):
        return self.name
            
class Signup(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    


        


user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import CharField, UUIDField
import uuid

# Create your models here.
class Profile(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE, blank=True, null=True)    
    

    name = models.CharField(max_length=200, blank=True, null=True)

    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True, default='This is the space for "Location"')

    email = models.EmailField(max_length=500, null=True, blank=True)
    short_intro = models.CharField(max_length = 150, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to="profile-pics/", default='profile-pics/default.jpg' )
    
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique= True , primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True,null=True)
    name = models.CharField(max_length=130, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique= True , primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)



user/forms.py
from django.contrib.auth.models import User
from django.forms import forms
from django.forms import models
from .models import Profile


class ProfileForm(models.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"



        # THIS IS TO CHANGE THE ATTRS IN THE FORM IN THE HTML FILE
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        self.fields['user'].widget.attrs.update({'class': 'input input--text', 'placeholder':"Add title"})

        self.fields['location'].widget.attrs.update({'class': 'input input--text', })
        self.fields['username'].widget.attrs.update({'class': 'input input--text', 'placeholder':"Username"})

        self.fields['email'].widget.attrs.update({'class': 'input input--text', 'placeholder':"Enter Email Here"})

        self.fields['short_intro'].widget.attrs.update({'class': 'input input--text', 'placeholder':"Short Intro"})

        self.fields['bio'].widget.attrs.update({'class': 'input input--text','placeholder':"Bio"})


        self.fields['social_github'].widget.attrs.update({'class': 'input input--text', 'placeholder':"Github Link"})

        self.fields['social_twitter'].widget.attrs.update({'class': 'input input--text', 'placeholder':"Twitter Link"})

        self.fields['social_website'].widget.attrs.update({'class': 'input input--text', 'placeholder':"Your Website"})
 

user/views.py
from django.http.response import HttpResponse
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm

from django.shortcuts import render, redirect


from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages as m 

# from django.contrib.messages import constants as messages

from .models import Profile, Skill 
from .forms import ProfileForm

@login_required(login_url='user:loginform')
def profile(request):
    profile = Profile.objects.all()
    # skills = Skill.objects.all()
    my_dict = {
        "profile" : profile,
        # "skills" : skills,
    }

    return render(request, "user/profile.html", my_dict)
    
def profileform(request):
    profile = ProfileForm
    my_dict = {
        "profile" : profile
    }

    return render(request, "user/profileform.html", my_dict)

def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)
    topskill = profile.skill_set.exclude(description__exact='')
    otherskill = profile.skill_set.filter(description='')
    print(profile.name)

    my_dict = {
        "profile":profile,
        "topskills":topskill,
        "profile":otherskill,
    }
    return render(request, "user/userprofile.html", my_dict)


def logoutUser(request):
    logout(request)
    m.error(request, 'User has successfully logged out')
    return redirect('user:loginform')

 
def myprofile(request):


    keys = {

    }
    return render(request, 'user/myprofile.html', keys)
    
def loginUser(request):
    if request.user.is_authenticated:
        return redirect('user:myprofile')
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        print(username)
        print(password)
        # try:
        #   user = User.objects.get(username = username)
        #   print('Username Exist!,Username is a GOOO')
        # except:
        #   m.error(request, 'Username Does Not Exist!')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            print('Username Or Password Is a GOOO!!!')
            return redirect('user:myprofile')
        else:
            m.error(request, 'Username Or Password Is incorrect')
    keys = {
    }
    return render(request, 'user/login.html', keys)
   

def signupUser(request):
    # if request.user.is_authenticated:
    #     return redirect('user:myprofile')

    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        # print(request.POST['username'])
        # print(request.POST['password1'])
        # print(request.POST['password2'])

        if form.is_valid():
            form = form.save(commit=False)
            form.username=form.username.lower()
            form.save()
            m.success(request, "Registration Successful")
            return redirect('user:myprofile')


    keys = {
        'signup' : form
    } 
    return render(request, 'user/signup.html', keys)
    
    


    
    
    
       

templates/user/login.html
<!DOCTYPE html>
{% extends "simple/base.html" %}
{% load static %}

{% block title %}
    login
{% endblock title %}
{% block things %}
<h1>This is the User Login</h1>

<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="{% url 'user:loginform' %}">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Account Login</h3>
        <p>Hello Developer, Welcome Back!</p>
      </div>

      <form  class="form auth__form" method="post">

          <div>
            {% if messages %}
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} {% endif %}
                    <div class="alert alert--error text--success">{{ message }}</div>
                </li>
                {% endfor %}
          {% endif %}
          </div>
          
          {% csrf_token %}
        <!-- Input:Username -->
        <div class="form__field">
          <label for="formInput#text">Username: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="username"
            placeholder="Enter your username..."
          />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="••••••••"
          />
        </div>
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
          <a href="forgetpassword.html">Forget Password?</a>
        </div>
      </form>
      <div class="auth__alternative">
        <p>Don’t have an Account?</p>
        <a href="{% url 'user:signup' %}">Sign Up</a>
      </div>
    </div>
  </div>
</main>

  
{% endblock things %}



templates/user/myprofile.html
<!DOCTYPE html>
{% extends "simple/base.html" %}
{% load static  %}
{% block things %}
<title>My Profile</title>

<h1><center>My Profile</center></h1>
<br>
<h1><center>Hello, {{user.username}}</center></h1>



{% endblock things %}


templates/user/profile.html
<!DOCTYPE html>
{% extends "simple/base.html" %}
{% load static  %}
{% block things %}
<title>User Profile</title>

<h1>This is the User Profiles</h1>
<main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
        {% for p in profile %}
           <div class="column card">
            <div class="dev">
              <a href="{% url 'user:userprofile' p.id %}" class="card__body" style="text-decoration: none;">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{p.profile_image.url}}" alt="image" />
                  
                  <div class="dev__meta">
                    <h3>{{p.name}}</h3>
                    <h5>{{p.short_intro}}</h5>
                    <!-- <h5>{{p.user.password}}</h5> -->
                  </div>
                </div>
                <p class="dev__info">
                    {{p.bio|slice:'500'}}
                </p>
                <div class="dev__skills">
                    {% for skill in p.skill_set.all %}
                        
                      <span class="tag tag--pill tag--main">
                          <small>{{skill}}</small>
                        </span>
                    {% endfor %}

                </div>
              </a>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
    </section>
</main>


{% endblock things %}


templates/user/profileform.html
<!DOCTYPE html>
{% extends "simple/base.html" %}

{% block title %}
  Profile Form
{% endblock title %}
{% block things %}
<h1>This is the User Profile Form</h1>

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'simple:database' %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    {% for field in profile %}
                      
                    <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{field.label}} </label>
                    {{field}}
                </div>
                {% endfor %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

  
{% endblock things %}



templates/user/signup.html
{% extends "simple/base.html" %}
{% block title %}
  signup
{% endblock title %}
{% block things %}

    <form method= 'POST' class="form auth__form">
        {% csrf_token %}
        <div class="form-group">
            {{signup.as_p}}
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Sign Up</button>
        </div>
    </form>
    
{% endblock things %}
<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="images/icon.svg" alt="icon" />
        </a>
        <h3>Account SignUp</h3>
        <p>Create a new developer account</p>
      </div>

      <form action="#" class="form auth__form">
        <!-- Input:Text -->
        <div class="form__field">
          <label for="formInput#text">Full Name: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="text"
            placeholder="e.g. Dennis Ivanov"
          />
        </div>

        <!-- Input:Email -->
        <div class="form__field">
          <label for="formInput#email">Email Address: </label>
          <input
            class="input input--email"
            id="formInput#email"
            type="email"
            name="email"
            placeholder="e.g. user@domain.com"
          />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="••••••••"
          />
        </div>
        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#confirm-password">Confirm Password: </label>
          <input
            class="input input--password"
            id="formInput#confirm-passowrd"
            type="password"
            name="confirm-password"
            placeholder="••••••••"
          />
        </div>
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
        </div>
      </form>
      <div class="auth__alternative">
        <p>Already have an Account?</p>
        <a href="{% url 'user:loginform' %}">Log In</a>
      </div>
    </div>
  </div>



templates/user/userprofile.html
<!DOCTYPE html>
{% extends "simple/base.html" %}
{% load static  %}
{% block things %}
<title>User Profile</title>
{{profile.name}}
<h1><center>User Profile</center></h1>

<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.location}}</p>
              <p class="dev__title">{{profile.email}}</p>
              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                    <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
                {% if profile.social_twitter %}
                  
                <li>
                    <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                {% endif %}
                {% if profile.social_website %}
                <li>
                    <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
                {% for skill in topskills %}
                  
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">
                    {{skill.description|slice:'150'}}
                </p>
              </div>
              {% endfor %}

              <h3 class="devInfo__subtitle">OTHER SKILLS</h3>
              
              {% for skill in otherskills %}
                <div class="devInfo__otherSkills">
                  <span class="tag tag--pill tag--sub tag--lg">
                      <small>{{skill.name}}</small>
                    </span>
                </div>
               {% endfor %}

            </div>
          </div>

          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
                {% for p in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="single-project.html" class="project">
                    <img class="project__thumbnail" src="{{p.featured_image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{p.title}}</h3>
                      <p><a class="project__author" href="profile.html">By {{p.owner}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{p.vote_ratio}}</span> Postitive
                        Feedback ({{p.vote_total}} Vote{{i.vote_total|pluralize:'s'}})
                      </p>
                      <div class="project__tags">
                        {% for tag in p.tag.all  %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock things %}
